name: Issue
description: Report a bug, typo, or missing content within one of our modules.
body:
  - type: markdown
    attributes:
      value: |
        Use this form to report an issue with a Loot Tavern module
  - type: dropdown
    id: report-type
    attributes:
      label: What kind of problem are you facing?
      options:
      - "Bug (something errors or does not work)"
      - "Typo (content has malformed or wrong text)"
      - "Missing Content (entire statblocks are missing)"
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: package
    attributes:
      label: What package are you reporting this for?
      description: Please tick both the adventure and the book a bug is in, ex. Motes of the Divine and Bones n Roses.
      multiple: true
      options:
      - "L'arsene Ledger of Treasures and Trinkets"
      - "Motes of the Divine"
      - "Bloodfrost of the Fey"
      - "Garden of Dark Delights"
      - "Ascent of the Sour Serpent"
      - "Queen of Shadow and Thorn"
      - "Forge of the Divine Machine"
      - "The Twilight Hunter"
      - "Flames of the Faithful"
      - "Bones n' Roses"
      - "Throne of the Devourer"
      - "LT01 - Sunken King"
      - "LT02 - Twisted Cults"
      - "LT03 - Frozen Norse"
      - "LT05 - Magitech Mayhem"
      - "LT06 - Welcome to the Jungle"
      - "LT08 - Body Augmentation"
      - "LT09 - Victorian Horror"
      - "LT10 - Antimagic Corruption"
      - "LT11 - High Seas Horror"
      - "LT12 - Ocean Kingdoms"
      - "LT13 - Mad Biomancer"
      - "LT14 - Fey Court"
      - "LT15 - Eastern Relics"
      - "LT16 - Nine Hells"
      - "LT17 - Astral Adventures"
      - "LT18 - Fantastical Bureau of Investigation"
      - "LT19 - Celestial Treasury"
      - "LT20 - Broodmother's Bounty"
      - "LT21 - The Iron Hoard"
      - "LT22 - The Low"
      - "LT23 - Mycelial Miscellany"
      - "LT24 - Elemental Explorers"
      - "LT25 - Junk and Mechatrash"
      - "LT26 - Advanced Arsenal"
      - "LT27 - Secrets of the Sunbear"
      - "LT28 - Treasures in the Tar"
      - "LT29 - Hospitaller's Hoard"
      - "LT30 - Hallow's Inn"
      - "LT31 - Dystopian Dreamscapes"
      - "LT32 - Draconic Armoury"
      - "LT33 - Relics of the Rakshasa"
      - "LT34 - Polyhedral Prizes"
      - "LT35 - Marvels of the Mimic Inn"
      - "LT36 - The Failed Gods"
      - "LT37 - Bonemonger's Artifice"
      - "LT38 - Unseelie Court"
      - "LT39 - Monstrous Magic Meals"
      - "LT40 - Magical Academy"
      - "LT41 - The Blademaster's Trove"
      - "LT42 - Hextech"
      - "LT43 - Monsters of Myth"
      - "LT44 - Twelve Days of Giftmas"
      - "LT45 - Metallurgy 101"
      - "LT46 - The Dark Carnival"
      - "LT47 - Patrons of Legend"
      - "LT48 - Thieves' Spoils"
      - "LT49 - Seasonal Armoury"
      - "LT50 - Unfathomable Terrors"
      - "LT51 - Dawn of the Yokai"
      - "LT52 - Cakewalk"
      - "LT53 - Rise of the Kaiju"
      - "LT54 - Prostheses and Enhancements"
      - "LT55 - Iconic Duos"
      - "Other?"
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of the package?
      placeholder: 1.0.0
    validations:
      required: true
