name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Use this form to report an issue with a Loot Tavern module
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: package
    attributes:
      label: What package are you reporting this for?
      multiple: false
      options:
      - "L'arsene Ledger of Treasures and Trinkets"
      - "Motes of the Divine"
      - "Bloodfrost of the Fey"
      - "Garden of Dark Delights"
      - "Ascent of the Sour Serpent"
      - "Queen of Shadow and Thorn"
      - "Forge of the Divine Machine"
      - "The Twilight Hunter"
      - "Flames of the Faithful"
      - "Bones n' Roses"
      - "Throne of the Devourer"
      - "Loot Tavern #1 - Sunken King"
      - "Loot Tavern #2 - Twisted Cults"
      - "Loot Tavern #3 - Frozen Norse"
      - "Loot Tavern #5 - Magitech Mayhem"
      - "Loot Tavern #6 - Welcome to the Jungle"
      - "Loot Tavern #8 - Body Augmentation"
      - "Loot Tavern #9 - Victorian Horror"
      - "Loot Tavern #10 - Antimagic Corruption"
      - "Loot Tavern #11 - High Seas Horror"
      - "Loot Tavern #12 - Ocean Kingdoms"
      - "Loot Tavern #13 - Mad Biomancer"
      - "Loot Tavern #14 - Fey Court"
      - "Loot Tavern #15 - Eastern Relics"
      - "Loot Tavern #16 - Nine Hells"
      - "Loot Tavern #17 - Astral Adventures"
      - "Loot Tavern #18 - Fantastical Bureau of Investigation"
      - "Loot Tavern #19 - Celestial Treasury"
      - "Loot Tavern #20 - Broodmother's Bounty"
      - "Loot Tavern #21 - The Iron Hoard"
      - "Loot Tavern #22 - The Low"
      - "Loot Tavern #23 - Mycelial Miscellany"
      - "Loot Tavern #24 - Elemental Explorers"
      - "Loot Tavern #25 - Junk and Mechatrash"
      - "Loot Tavern #26 - Advanced Arsenal"
      - "Loot Tavern #27 - Secrets of the Sunbear"
      - "Loot Tavern #28 - Treasures in the Tar"
      - "Loot Tavern #29 - Hospitaller's Hoard"
      - "Loot Tavern #30 - Hallow's Inn"
      - "Loot Tavern #31 - Dystopian Dreamscapes"
      - "Loot Tavern #32 - Draconic Armoury"
      - "Loot Tavern #33 - Relics of the Rakshasa"
      - "Loot Tavern #34 - Polyhedral Prizes"
      - "Loot Tavern #35 - Marvels of the Mimic Inn"
      - "Loot Tavern #36 - The Failed Gods"
      - "Loot Tavern #37 - Bonemonger's Artifice"
      - "Loot Tavern #38 - Unseelie Court"
      - "Loot Tavern #39 - Monstrous Magic Meals"
      - "Loot Tavern #40 - Magical Academy"
      - "Loot Tavern #41 - The Blademaster's Trove"
      - "Loot Tavern #42 - Hextech"
      - "Loot Tavern #43 - Monsters of Myth"
      - "Loot Tavern #44 - Twelve Days of Giftmas"
      - "Loot Tavern #45 - Metallurgy 101"
      - "Loot Tavern #46 - The Dark Carnival"
      - "Loot Tavern #47 - Patrons of Legend"
      - "Loot Tavern #48 - Thieves' Spoils"
      - "Loot Tavern #49 - Seasonal Armoury"
      - "Loot Tavern #50 - Unfathomable Terrors"
      - "Loot Tavern #51 - Dawn of the Yokai"
      - "Loot Tavern #52 - Cakewalk"
      - "Loot Tavern #53 - Wrath of the Kaiju"
      - "Loot Tavern #54 - Prostheses and Enhancements"
      - "Loot Tavern #55 - Iconic Duos"
      - "Other?"
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of the package?
      placeholder: 1.0.0
    validations:
      required: true
